### ISSUE TITLE
SVO's Encrypted Traffic Is Called “Medius”

### ISSUE THREAD

**Issue by JonHypersomniac** [JonHypersomniac/warhawk#1]
The name “Medius” is actually the real name of what what *we* call “GAYSSL” — which was given upon initial discovery. As a compromise between the two names, the final name shall ultimately be called “Gayius” in all of the code and documentation.

**Comment by Hopefullyidontgetbanned** [comment]
Interesting that the traffic is actually encrypted considering how weak server security is
